Este curso é de propriedade do aplicativo [SoloLearn](https://play.google.com/store/apps/details?id=com.sololearn) e foi traduzido por [Ana Beatriz Augusto](https://www.linkedin.com/in/anabeatrizz) usando os recursos [Reverso Context](https://context.reverso.net/translation/) e [Google Tradutor](https://translate.google.com.br/?hl=pt-BR)

# Índice
- [Exceções](#exceções)
- [Tratando exceções](#tratando-exceções)
- [finally](#finally)
- [Chamando exceções](#chamando-exceções)
- [Asserções](#asserções)
- [Abrindo arquivos](#abrindo-arquivos)
- [Lendo arquivos](#lendo-arquivos)
- [Escrevendo em arquivos](#escrevendo-em-arquivos)
- [Trabalhando com arquivos](#trabalhando-com-arquivos)

# [Exceções](#índice)
Nós já vimos __exceções__ em códigos anteriores. Ocorrem quando algo dá errado, devido a código incorreto ou entrada incorreta. Quando uma exceção ocorre, o programa para imediatamente.<br>O seguinte código produz a exceção `ZeroDivisionError` quando se tenta dividir 7 por 0.
```python
num1 = 7
num2 = 0
print(num1 / num2)
```

__Resultado:__
```python
>>>
ZeroDivisionError: division by zero
>>>
```

Diferentes exceções são criadas por diferentes motivos.<br>Exceções comuns:<br>`ImportError`: falha na importação;<br>`IndexError`: uma lista está indexada com um numero fora do intervalo;<br>`NameError`: uma variável desconhecida é usada;<br>`SyntaxError`: o código não pode ser analisado corretamente;<br>`TypeError`: uma função é chamada em um valor de tipo inapropriado;<br>`ValueError`: uma função é chamada em um valor de tipo correto, mas com um valor inapropriado.

O Python tem várias outras exceções embutidas, como `ZeroDivisionError` e `OSError`. Bibliotecas de terceiros frequentemente também definem suas proprias exceções.

# [Tratando exceções](#índices)
Para se trata exceções e chama código quando uma exceção ocorre, você pode usar `try`/`except`.<br>O bloco `try` contém código onde talvez ocorra uma exceção. Se essa exceção ocorrer, o código dentro do bloco `try` para de ser executado e o código no bloco `except` é executado. Se nenhum erro ocorrer, o código no bloco `except` não se executa.<br>__Por exemplo:__
```python
try:
   num1 = 7
   num2 = 0
   print(num1 / num2)
   print("Cálculo feito")
except ZeroDivisionError:
   print("Um erro ocorreu")
   print("devido pela divisão por zero")
```

__Resultado:__
```python
>>>
Um erro ocorreu
devido pela divisão por zero
>>>
```

No código acima, o `except` define o tipo de exceção para se tratar (neste caso, `ZeroDivisionError`).

Um `try` pode ter vários blocos `except` diferentes para tratar diferentes exceções.<br>Multiplas exceções também podem ser colocadas em um unico bloco `except` usando parenteses, para o bloco `except` tratar todas elas.
```python
try:
   variavel = 10
   print(variavel + "olá")
   print(variavel / 2)
except ZeroDivisionError:
   print("Dividido por zero")
except (ValueError, TypeError):
   print("Um erro ocorreu")
```

__Resultado:__
```python
>>>
Um erro ocorreu
>>>
```

Um `except` sem qualquer exceção especificada irá pegar todos os erros. Estes devem ser usados moderadamente, pois eles podem pegar erros inesperados e esconder erros de programação.<br>__Por exemplo:__
```python
try:
   palavra = "spam"
   print(palavra / 0)
except:
   print("Um erro ocorreu")
```

__Resultado:__
```python
>>>
Um erro ocorreu
>>>
```

Tratar exceções é particularmente util quando se lida com entrada de usuário.

# [finally](#índice)
Para ter certeza que algum código irá ser executado não importando qual erro aconteça, você pode usar `finally`. Ele é colocado no fim de `try`/`except`. Código dentro de um `finally` sempre se executa depois da execução do código no bloco `try` e possivelmente do bloco `except`.
```python
try:
   print("Olá")
   print(1 / 0)
except ZeroDivisionError:
   print("Dividido por zero")
finally:
   print("Este código será exectado não importando o que aconteça")
```

__Resultado:__
```python
>>>
Olá
Dividido por zero
Este código será exectado não importando o que aconteça
>>>
```

Código dentro de um `finally` se executa até mesmo quando uma exceção não pega ocorrer em um dos blocos anteriores.
```python
try:
   print(1)
   print(10 / 0)
except ZeroDivisionError:
   print(variavel_desconhecida)
finally:
   print("Isso é executado por ultimo")
```

__Resultado:__
```python
>>>
1
Isso é executado por ultimo

ZeroDivisionError: division by zero
During handling of the above exception, another exception occurred:
NameError: name 'unknown_var' is not defined
>>>
```

# [Chamando exceções](#índice)
Você pode chamar exceções usando `raise`.
```python
print(1)
raise ValueError
print(2)
```

__Resultado:__
```python
>>>
1
ValueError
>>>
```

Você precisa especificar o __tipo__ de exceção que deseja chamar.

Exceções podem ser chamadas com argumentos que dão detalhes sobre elas.<br>__Por exemplo:__
```python
nome = "123"
raise NameError("Nome inválido!")
```

__Resultado:__
```python
>>>
NameError: Nome inválido!
>>>
```

Em blocos `except`, o `raise` pode ser usado sem argumentos para chamar novamente qualquer exceção que acontecer.<br>__Por exemplo:__
```python
try:
   num = 5 / 0
except:
   print("Um erro ocorreu")
   raise
```

__Resultado:__
```python
>>>
Um erro ocorreu

ZeroDivisionError: division by zero
>>>
```

# [Asserções](#índice)
Uma __asserção__ é uma verificação de normalidade que você pode ligar ou desligar quando terminar de testar seu programa.<br>Uma expressão é testada e se o resultado for falso, uma exceção é chamada.<br>Asserções são executadas através do uso de `assert`.
```python
print(1)
assert 2 + 2 == 4
print(2)
assert 1 + 1 == 3
print(3)
```

__Resultado:__
```python
>>>
1
2
AssertionError
>>>
```

Programadores frequentemente colocam asserções no começo de uma função para verificar entradas e depois de uma chamada de função para verificar saídas.

`assert` pode levar um segundo argumento que é passado ao AssertionError, chamado quando a asserção falha.
```python
temp = -10
assert (temp >= 0), "Mais frio que zero absoluto!"
```

__Resultado:__
```python
>>>
AssertionError: Mais frio que zero absoluto!
>>>
```

Exceções AssertionError podem ser pegas e tratadas como qualquer outra exceção usando `try`/`except`, mas se não tratadas, este tipo de exceção irá terminar o programa.

# [Abrindo arquivos](#índice)
Você pode usar Python para ler e escrever o conteúdo de __arquivos__.<br>Arquivos de texto são os mais fáceis de manipular. Antes de poder editar um arquivo, ele deve estar aberto usando a função `open`.
```python
meuarquivo = open("nomedoarquivo.txt")
```

O argumento da função `open` é o __caminho__ do arquivo. Se o arquivo está no mesmo diretório do programa, você pode especificar apenas seu nome.

Você pode especificar o __modo__ usado para abrir um arquivo aplicando um segundo argumento à função `open`.<br>`r` significa abrir em modo de leitura, que é o padrão.<br>`w` significa modo de escrita, para reescrever o conteúdo de um arquivo.<br>`a` significa modo de adição, para adicionar novo conteúdo no fim do arquivo.

Adicionar `b` à um modo, abre o arquivo em modo __binário__, que é usado para arquivos não textuais (como imagens e arquivos de som).<br>__Por exemplo:__
```python
# modo de escrita
open("nomedoarquivo.txt", "w")

# modo de leitura
open("nomedoarquivo.txt", "r")
open("nomedoarquivo.txt")

# modo de escrita binária
open("nomedoarquivo.txt", "wb")
```

Você pode usar o sinal `+` com cada modo acima para dar um acesso extra aos arquivos. Por exemplo, `r+` abre o arquivo para leitura e escrita.

Uma vez que o arquivo foi aberto e usado, você deve fechá-lo.<br>Isso é feito usando o método `close` do objeto do arquivo.
```python
arquivo = open("nomedoarquivo.txt", "w")
# faça algo com o arquivo
arquivo.close()
```

# [Lendo arquivos](#índice)
O conteúdo de um arquivo que foi aberto em modo texto pode ser lido usando o metodo `read`.
```python
arquivo = open("nomedoarquivo.txt", "r")
conteudo = arquivo.read()
print(conteudo)
arquivo.close()
```

Este código irá mostrar o conteúdo do arquivo "nomedoarquivo.txt".

Para ler apenas uma certa quantidade de um arquivo, você pode fornecer um numero como argumento para a função `read`. Isso determina o numero de __bytes__ que devem ser lidos.<br>Você pode fazer mais chamadas ao `read` no mesmo objeto de arquivo para ler mais do arquivo byte por byte. Com nenhum argumento, `read` retorna o resto do arquivo.
```python
arquivo = open("nomedoarquivo.txt", "r")
print(arquivo.read(16))
print(arquivo.read(4))
print(arquivo.read(4))
print(arquivo.read())
arquivo.close()
```

Valores negativos retornarão o conteúdo inteiro.

Depois que todo conteúdo de um arquivo foi lido, qualquer tentativa de lê-lo novamente retornará uma string vazia, pois você está tentando ler a partir do fim do arquivo.
```python
arquivo = open("nomedoarquivo.txt", "r")
arquivo.read()
print("Relendo")
print(arquivo.read())
print("Finalizado")
arquivo.close()
```

__Resultado:__
```python
>>>
Relendo

Finalizado
>>>
```

Para mostrar cada linha de um arquivo, você pode usar o metodo `readlines` para retornar uma lista que terá uma linha em cada elemento.<br>__Por exemplo:__
```python
arquivo = open("nomedoarquivo.txt", "r")
print(arquivo.readlines())
arquivo.close()
```

__Resultado:__
```python
>>>
['Linha 1 texto \n', 'Linha 2 texto \n', 'Linha 3 texto']
>>>
```

Você também pode usar um ciclo `for` para iterar atraves das linhas do arquivo:
```python
arquivo = open("nomedoarquivo.txt", "r")

for linha in arquivo:
    print(linha)

arquivo.close() 
```

__Resultado:__
```python
>>>
Linha 1 texto

Linha 2 texto

Linha 3 texto
>>>
```

No resultado, as linhas são separadas por linhas em branco, pois a função `print` automaticamente adiciona uma nova linha no fim do resultado.

# [Escrevendo em arquivos](#índice)
Para escrever em arquivos você usa o metodo `write` que escreve uma string no arquivo.<br>__Por exemplo:__
```python
arquivo = open("novoarquivo.txt", "w")
arquivo.write("Isso foi escrito no arquivo")
arquivo.close()

arquivo = open("novoarquivo.txt", "r")
print(arquivo.read())
arquivo.close()
```

__Resultado:__
```python
>>>
Isso foi escrito no arquivo
>>>
```

O modo `w` irá criar um arquivo, se ele não existir.

Quando um arquivo está aberto no modo de escrita, o conteudo existente do arquivo é deletado.
```python
arquivo = open("novoarquivo.txt", "r")
print("Lendo conteudo inicial")
print(arquivo.read())
print("Finalizado")
arquivo.close()

arquivo = open("novoarquivo.txt", "w")
arquivo.write("Novo texto")
arquivo.close()

arquivo = open("novoarquivo.txt", "r")
print("Lendo novo conteudo")
print(arquivo.read())
print("Finalizado")
arquivo.close()
```

__Resultado:__
```python
>>>
Lendo conteudo inicial
algum texto inicial
Finalizado
Lendo novo conteudo
Novo texto
Finalizado
>>>
```

Como podemos ver, o conteudo do arquivo foi sobrescrito.

O metodo `write` retorna o numero de __bytes__ escritos em um arquivo, se tiver sucesso.
```python
msg = "Olá mundo!"
arquivo = open("novoarquivo.txt", "w")
qtd_escrita = arquivo.write(msg)
print(qtd_escrita)
arquivo.close()
```

__Resultado:__
```python
>>>
12
>>>
```

Para escrever algo diferente de uma string, precisa ser convertido para uma string primeiro.

# [Trabalhando com arquivos](#índice)
É uma boa pratica evitar o gasto de recursos tendo certeza que arquivos sempre serão fechados depois de usados. Uma maneira de fazer isso é usar `try` e `finally`.
```python
try:
   f = open("nomedoarquivo.txt")
   print(f.read())
finally:
   f.close()
```

Isso dá a certeza de que o arquivo é sempre fechado, mesmo se um erro ocorrer.

Outra maneira de fazer isso é usar `with`. Ele cria uma variavel temporaria (frequentemente chamada de f), que apenas é acessivel no bloco indentado do `with`.
```python
with open("nomedoarquivo.txt") as f:
   print(f.read())
```

O arquivo é fechado automaticamente no fim do `with`, mesmo se exceções ocorrerem dentro dele.

Este curso é de propriedade do aplicativo [SoloLearn](https://play.google.com/store/apps/details?id=com.sololearn) e foi traduzido por [Ana Beatriz Augusto](https://www.linkedin.com/in/anabeatrizz) usando os recursos [Reverso Context](https://context.reverso.net/translation/) e [Google Tradutor](https://translate.google.com.br/?hl=pt-BR)
